# Generated by Django 5.1.1 on 2024-10-02 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocator', '0003_alter_restaurant_place_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AddField(
            model_name='favorite',
            name='restaurant_name',
            field=models.CharField(default=9999999999999, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='restaurant',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'restaurant')},
        ),
    ]
