# Generated by Django 5.1.1 on 2024-10-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geolocator", "0003_alter_favorite_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="restaurant_name",
            field=models.CharField(default=999999999999999, max_length=500),
            preserve_default=False,
        ),
    ]
