# Generated by Django 5.1.1 on 2024-10-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geolocator", "0005_alter_favorite_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="restaurant_name",
            field=models.CharField(default=9999999999, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="favorite",
            name="restaurant",
            field=models.CharField(max_length=255),
        ),
    ]
